config/routes.rb
Rails.application.routes.draw do
	get 'sessions/new'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :candidats, :companies
	root to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidat.rb
class Candidat < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :candidats, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :show_flash

  private

  def show_flash
  end
end

app/controllers/candidats_controller.rb
class CandidatsController < ApplicationController
  before_action :set_candidat, only: [:destroy]

  # GET /candidats
  # GET /candidats.json
  def index
    @candidats = Candidat.all
  end

  # GET /candidats/new
  def new
    @candidat = Candidat.new
  end

  # POST /candidats
  # POST /candidats.json
  def create
    @candidat = Candidat.new(candidat_params)
    respond_to do |format|
      if @candidat.save
		ApplicationMailer.send_email(@candidat).deliver
        format.html { redirect_to candidats_url, notice: 'Candidat créé avec succès.' }
        format.json { render :show, status: :created, location: @candidat }
      else
        format.html { render :new }
        format.json { render json: @candidat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidats/1
  # DELETE /candidats/1.json
  def destroy
    @candidat.destroy
    respond_to do |format|
      format.html { redirect_to candidats_url, notice: 'Candidat supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidat
      @candidat = Candidat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidat_params
      params.require(:candidat).permit(:nom, :email, :photo, :company_id)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: 'Entreprise créée avec succès.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Entreprise supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:nom)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    if (params[:session][:email] == 'contact@rebhi-services.com' && params[:session][:password] == '$admin1234$')
		log_in
		redirect_to candidats_url
    else
		flash.now[:danger] = 'Email ou mot de passe invalide'
		render 'new'
    end
  end

  def destroy
	log_out
	redirect_to root_path
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidats_helper.rb
module CandidatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in()
		session[:user_id] = 'loggedIN'
	end
	
	def log_out()
		session[:user_id] = nil
	end
end

app/views/candidats/_form.html.erb
<%= form_for(@candidat) do |f| %>
  <% if @candidat.errors.any? %>
    <div id="error_explanation">
      <h2>Une erreur est survenue lors de l'ajout du candidat:</h2>

      <ul>
      <% @candidat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom, :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, :required => true %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo, :required => true %>
  </div>
  <div class="field">
  <%= f.label 'Entreprise' %><br>
  <%= f.collection_select :company_id, Company.all, :id, :nom %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit :id => "new_cand_submit", :value => "Valider", 'data-disable-with' => "Veuillez patientez..." %>
  </div>
  <script>
  $(function(){
	if($('#candidat_nom').val().length < 4 || $('#candidat_email').val().length < 4) 
	   $('#new_cand_submit').attr('disabled', true);

	$('#candidat_nom').on('change paste keyup', function(){
		if($('#candidat_nom').val().length >= 4 && $('#candidat_email').val().length >= 4) 
			 $('#new_cand_submit').attr('disabled', false);    
		else
			 $('#new_cand_submit').attr('disabled', true);   
	});
	
	$('#candidat_email').on('change paste keyup', function(){
		if($('#candidat_nom').val().length >= 4 && $('#candidat_email').val().length >= 4) 
			 $('#new_cand_submit').attr('disabled', false);    
		else
			 $('#new_cand_submit').attr('disabled', true);   
	});
});
  </script>
<% end %>

app/views/candidats/index.html.erb
<% if @candidats.blank? %>
<h1>Aucun candidat n'est encore ajouté!!</h1>
<br>
<% else %>
<h1>Liste des candidats</h1>
<div style="overflow-x:auto;">
<table class="list_candidats" border=1>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Email</th>
      <th>Photo</th>
      <th>Entreprise</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @candidats.each do |candidat| %>
      <tr>
        <td><%= candidat.nom %></td>
        <td><%= candidat.email %></td>
        <td><img src=<%= candidat.photo %> width = '250' /></td>
        <td><%= candidat.company.nom %></td>
        <td><%= link_to 'Supprimer', candidat, method: :delete, data: { confirm: 'Etes vous sûr de vouloir supprimer ce candidat?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<% end %>

app/views/candidats/new.html.erb
<h1>Nouveau Candidat</h1>

<%= render 'form' %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>Une erreur est survenue lors de l'ajout de l'entreprise:</h2>

      <ul>
      <% @candidat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom, :required => true %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit :id => "new_company_submit", :value => "Valider", 'data-disable-with' => "Veuillez patientez..." %>
  </div>
  <script>
  $(function(){
	if($('#company_nom').val().length < 3) 
	   $('#new_company_submit').attr('disabled', true);

	$('#company_nom').on('change paste keyup', function(){
		if($('#company_nom').val().length >= 3) 
			 $('#new_company_submit').attr('disabled', false);    
		else
			 $('#new_company_submit').attr('disabled', true);   
	});
});
  </script>
<% end %>

app/views/companies/index.html.erb
<% if @companies.blank? %>
<h1>Aucune entreprise n'est encore ajoutée!!</h1>
<br>
<% else %>
<h1>Liste des entreprises</h1>
<div style="overflow-x:auto;">
<table class="list_candidats" border=1>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.nom %></td>
        <td><%= link_to 'Supprimer', company, method: :delete, data: { confirm: 'Etes vous sûr de vouloir supprimer cette entreprise?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<% end %>

app/views/companies/new.html.erb
<h1>Nouvelle Entreprise</h1>

<%= render 'form' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
	<header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">SELECTEEV.IO</h1>
                <hr>
                
                Plateforme de candidature
				<br><br>
            </div>
        </div>
	</header>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Accueil", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
	
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if session[:user_id] %>
<li class='nav-item'><%= link_to 'Candidats', url_for(action: 'index', controller: 'candidats'), class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Entreprises', url_for(action: 'index', controller: 'companies'), class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Inscrire candidat', new_candidat_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Inscrire entreprise', new_company_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
<% else %>
<li class='nav-item'><%= link_to 'Inscrire candidat', new_candidat_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Inscrire entreprise', new_company_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Login', login_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Selecteev RoR Test" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Selecteev RoR Test" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
	<br>
	<footer>
		Copyright Salem Rebhi 
	</footer>

  </body>
</html>

app/views/pages/candidats.html.erb
<% content_for :title do %>About<% end %>

<div class="jumbotron">
  <h1 class="display-4">About the Website</h1>
  <p class="lead">
    This web application was created with
    <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
    from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>
</div>

app/views/visitors/index.html.erb
	<%= nivo_slider id: "slider" do %>
		<%= image_tag "https://citizenlab.co/blog/wp-content/uploads/2016/10/o-STARTUP-facebook.jpg", title: "Lancez votre startup!" %>
		<%= image_tag "https://thenextweb.com/wp-content/blogs.dir/1/files/2013/10/Startup-idea-building.jpg", title: "Nous organisons vos évènements..." %>
	<% end %>